name = "CellwiseValues"
uuid = "32aff420-fa03-5903-8c38-4691cd106de7"
authors = ["fverdugo <fverdugo@cimne.upc.edu>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
